//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cliente_WEB_Ventas.ProxyVendedor {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="VendedorDC", Namespace="http://schemas.datacontract.org/2004/07/WCF_Ventas")]
    [System.SerializableAttribute()]
    public partial class VendedorDC : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Ape_venField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ApellNom_SupervisorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Cod_SupervisorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Cod_venField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DNI_venField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Email_venField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> Est_venField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EstadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> Fec_RegistroField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> Fec_Ult_ModField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime Fec_ingField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Nom_venField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> Sue_venField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private short Tip_venField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Usu_RegistroField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Usu_Ult_ModField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Ape_ven {
            get {
                return this.Ape_venField;
            }
            set {
                if ((object.ReferenceEquals(this.Ape_venField, value) != true)) {
                    this.Ape_venField = value;
                    this.RaisePropertyChanged("Ape_ven");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ApellNom_Supervisor {
            get {
                return this.ApellNom_SupervisorField;
            }
            set {
                if ((object.ReferenceEquals(this.ApellNom_SupervisorField, value) != true)) {
                    this.ApellNom_SupervisorField = value;
                    this.RaisePropertyChanged("ApellNom_Supervisor");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Cod_Supervisor {
            get {
                return this.Cod_SupervisorField;
            }
            set {
                if ((object.ReferenceEquals(this.Cod_SupervisorField, value) != true)) {
                    this.Cod_SupervisorField = value;
                    this.RaisePropertyChanged("Cod_Supervisor");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Cod_ven {
            get {
                return this.Cod_venField;
            }
            set {
                if ((object.ReferenceEquals(this.Cod_venField, value) != true)) {
                    this.Cod_venField = value;
                    this.RaisePropertyChanged("Cod_ven");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DNI_ven {
            get {
                return this.DNI_venField;
            }
            set {
                if ((object.ReferenceEquals(this.DNI_venField, value) != true)) {
                    this.DNI_venField = value;
                    this.RaisePropertyChanged("DNI_ven");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email_ven {
            get {
                return this.Email_venField;
            }
            set {
                if ((object.ReferenceEquals(this.Email_venField, value) != true)) {
                    this.Email_venField = value;
                    this.RaisePropertyChanged("Email_ven");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Est_ven {
            get {
                return this.Est_venField;
            }
            set {
                if ((this.Est_venField.Equals(value) != true)) {
                    this.Est_venField = value;
                    this.RaisePropertyChanged("Est_ven");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Estado {
            get {
                return this.EstadoField;
            }
            set {
                if ((object.ReferenceEquals(this.EstadoField, value) != true)) {
                    this.EstadoField = value;
                    this.RaisePropertyChanged("Estado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> Fec_Registro {
            get {
                return this.Fec_RegistroField;
            }
            set {
                if ((this.Fec_RegistroField.Equals(value) != true)) {
                    this.Fec_RegistroField = value;
                    this.RaisePropertyChanged("Fec_Registro");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> Fec_Ult_Mod {
            get {
                return this.Fec_Ult_ModField;
            }
            set {
                if ((this.Fec_Ult_ModField.Equals(value) != true)) {
                    this.Fec_Ult_ModField = value;
                    this.RaisePropertyChanged("Fec_Ult_Mod");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Fec_ing {
            get {
                return this.Fec_ingField;
            }
            set {
                if ((this.Fec_ingField.Equals(value) != true)) {
                    this.Fec_ingField = value;
                    this.RaisePropertyChanged("Fec_ing");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nom_ven {
            get {
                return this.Nom_venField;
            }
            set {
                if ((object.ReferenceEquals(this.Nom_venField, value) != true)) {
                    this.Nom_venField = value;
                    this.RaisePropertyChanged("Nom_ven");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> Sue_ven {
            get {
                return this.Sue_venField;
            }
            set {
                if ((this.Sue_venField.Equals(value) != true)) {
                    this.Sue_venField = value;
                    this.RaisePropertyChanged("Sue_ven");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short Tip_ven {
            get {
                return this.Tip_venField;
            }
            set {
                if ((this.Tip_venField.Equals(value) != true)) {
                    this.Tip_venField = value;
                    this.RaisePropertyChanged("Tip_ven");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Usu_Registro {
            get {
                return this.Usu_RegistroField;
            }
            set {
                if ((object.ReferenceEquals(this.Usu_RegistroField, value) != true)) {
                    this.Usu_RegistroField = value;
                    this.RaisePropertyChanged("Usu_Registro");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Usu_Ult_Mod {
            get {
                return this.Usu_Ult_ModField;
            }
            set {
                if ((object.ReferenceEquals(this.Usu_Ult_ModField, value) != true)) {
                    this.Usu_Ult_ModField = value;
                    this.RaisePropertyChanged("Usu_Ult_Mod");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ProxyVendedor.IServicioVendedor")]
    public interface IServicioVendedor {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioVendedor/ConsultarVendedor", ReplyAction="http://tempuri.org/IServicioVendedor/ConsultarVendedorResponse")]
        Cliente_WEB_Ventas.ProxyVendedor.VendedorDC ConsultarVendedor(string strCodigo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioVendedor/ConsultarVendedor", ReplyAction="http://tempuri.org/IServicioVendedor/ConsultarVendedorResponse")]
        System.Threading.Tasks.Task<Cliente_WEB_Ventas.ProxyVendedor.VendedorDC> ConsultarVendedorAsync(string strCodigo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioVendedor/ListarVendedor", ReplyAction="http://tempuri.org/IServicioVendedor/ListarVendedorResponse")]
        Cliente_WEB_Ventas.ProxyVendedor.VendedorDC[] ListarVendedor();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioVendedor/ListarVendedor", ReplyAction="http://tempuri.org/IServicioVendedor/ListarVendedorResponse")]
        System.Threading.Tasks.Task<Cliente_WEB_Ventas.ProxyVendedor.VendedorDC[]> ListarVendedorAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioVendedor/InsertarVendedor", ReplyAction="http://tempuri.org/IServicioVendedor/InsertarVendedorResponse")]
        bool InsertarVendedor(Cliente_WEB_Ventas.ProxyVendedor.VendedorDC objVendedorDC);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioVendedor/InsertarVendedor", ReplyAction="http://tempuri.org/IServicioVendedor/InsertarVendedorResponse")]
        System.Threading.Tasks.Task<bool> InsertarVendedorAsync(Cliente_WEB_Ventas.ProxyVendedor.VendedorDC objVendedorDC);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioVendedor/ActualizarVendedor", ReplyAction="http://tempuri.org/IServicioVendedor/ActualizarVendedorResponse")]
        bool ActualizarVendedor(Cliente_WEB_Ventas.ProxyVendedor.VendedorDC objVendedorDC);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioVendedor/ActualizarVendedor", ReplyAction="http://tempuri.org/IServicioVendedor/ActualizarVendedorResponse")]
        System.Threading.Tasks.Task<bool> ActualizarVendedorAsync(Cliente_WEB_Ventas.ProxyVendedor.VendedorDC objVendedorDC);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioVendedor/EliminarVendedor", ReplyAction="http://tempuri.org/IServicioVendedor/EliminarVendedorResponse")]
        bool EliminarVendedor(string strCodigo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioVendedor/EliminarVendedor", ReplyAction="http://tempuri.org/IServicioVendedor/EliminarVendedorResponse")]
        System.Threading.Tasks.Task<bool> EliminarVendedorAsync(string strCodigo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioVendedor/ListarSupervisores", ReplyAction="http://tempuri.org/IServicioVendedor/ListarSupervisoresResponse")]
        Cliente_WEB_Ventas.ProxyVendedor.VendedorDC[] ListarSupervisores();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioVendedor/ListarSupervisores", ReplyAction="http://tempuri.org/IServicioVendedor/ListarSupervisoresResponse")]
        System.Threading.Tasks.Task<Cliente_WEB_Ventas.ProxyVendedor.VendedorDC[]> ListarSupervisoresAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServicioVendedorChannel : Cliente_WEB_Ventas.ProxyVendedor.IServicioVendedor, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServicioVendedorClient : System.ServiceModel.ClientBase<Cliente_WEB_Ventas.ProxyVendedor.IServicioVendedor>, Cliente_WEB_Ventas.ProxyVendedor.IServicioVendedor {
        
        public ServicioVendedorClient() {
        }
        
        public ServicioVendedorClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServicioVendedorClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioVendedorClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioVendedorClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Cliente_WEB_Ventas.ProxyVendedor.VendedorDC ConsultarVendedor(string strCodigo) {
            return base.Channel.ConsultarVendedor(strCodigo);
        }
        
        public System.Threading.Tasks.Task<Cliente_WEB_Ventas.ProxyVendedor.VendedorDC> ConsultarVendedorAsync(string strCodigo) {
            return base.Channel.ConsultarVendedorAsync(strCodigo);
        }
        
        public Cliente_WEB_Ventas.ProxyVendedor.VendedorDC[] ListarVendedor() {
            return base.Channel.ListarVendedor();
        }
        
        public System.Threading.Tasks.Task<Cliente_WEB_Ventas.ProxyVendedor.VendedorDC[]> ListarVendedorAsync() {
            return base.Channel.ListarVendedorAsync();
        }
        
        public bool InsertarVendedor(Cliente_WEB_Ventas.ProxyVendedor.VendedorDC objVendedorDC) {
            return base.Channel.InsertarVendedor(objVendedorDC);
        }
        
        public System.Threading.Tasks.Task<bool> InsertarVendedorAsync(Cliente_WEB_Ventas.ProxyVendedor.VendedorDC objVendedorDC) {
            return base.Channel.InsertarVendedorAsync(objVendedorDC);
        }
        
        public bool ActualizarVendedor(Cliente_WEB_Ventas.ProxyVendedor.VendedorDC objVendedorDC) {
            return base.Channel.ActualizarVendedor(objVendedorDC);
        }
        
        public System.Threading.Tasks.Task<bool> ActualizarVendedorAsync(Cliente_WEB_Ventas.ProxyVendedor.VendedorDC objVendedorDC) {
            return base.Channel.ActualizarVendedorAsync(objVendedorDC);
        }
        
        public bool EliminarVendedor(string strCodigo) {
            return base.Channel.EliminarVendedor(strCodigo);
        }
        
        public System.Threading.Tasks.Task<bool> EliminarVendedorAsync(string strCodigo) {
            return base.Channel.EliminarVendedorAsync(strCodigo);
        }
        
        public Cliente_WEB_Ventas.ProxyVendedor.VendedorDC[] ListarSupervisores() {
            return base.Channel.ListarSupervisores();
        }
        
        public System.Threading.Tasks.Task<Cliente_WEB_Ventas.ProxyVendedor.VendedorDC[]> ListarSupervisoresAsync() {
            return base.Channel.ListarSupervisoresAsync();
        }
    }
}
