//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebTestWCF_Infracciones.ProxyInfracciones {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ProxyInfracciones.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ListarPapeletasAuto_Fechas", ReplyAction="http://tempuri.org/IService1/ListarPapeletasAuto_FechasResponse")]
        System.Data.DataSet ListarPapeletasAuto_Fechas(string numPlaca, System.DateTime fecIni, System.DateTime fecFin);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ListarPapeletasAuto_Fechas", ReplyAction="http://tempuri.org/IService1/ListarPapeletasAuto_FechasResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> ListarPapeletasAuto_FechasAsync(string numPlaca, System.DateTime fecIni, System.DateTime fecFin);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/EstadisticaMultas_AutoMensual", ReplyAction="http://tempuri.org/IService1/EstadisticaMultas_AutoMensualResponse")]
        System.Data.DataSet EstadisticaMultas_AutoMensual(string numPlaca, short año);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/EstadisticaMultas_AutoMensual", ReplyAction="http://tempuri.org/IService1/EstadisticaMultas_AutoMensualResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> EstadisticaMultas_AutoMensualAsync(string numPlaca, short año);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/EstadisticaPapeletas_AutoAnual", ReplyAction="http://tempuri.org/IService1/EstadisticaPapeletas_AutoAnualResponse")]
        System.Data.DataSet EstadisticaPapeletas_AutoAnual(string numPlaca);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/EstadisticaPapeletas_AutoAnual", ReplyAction="http://tempuri.org/IService1/EstadisticaPapeletas_AutoAnualResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> EstadisticaPapeletas_AutoAnualAsync(string numPlaca);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : WebTestWCF_Infracciones.ProxyInfracciones.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<WebTestWCF_Infracciones.ProxyInfracciones.IService1>, WebTestWCF_Infracciones.ProxyInfracciones.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataSet ListarPapeletasAuto_Fechas(string numPlaca, System.DateTime fecIni, System.DateTime fecFin) {
            return base.Channel.ListarPapeletasAuto_Fechas(numPlaca, fecIni, fecFin);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> ListarPapeletasAuto_FechasAsync(string numPlaca, System.DateTime fecIni, System.DateTime fecFin) {
            return base.Channel.ListarPapeletasAuto_FechasAsync(numPlaca, fecIni, fecFin);
        }
        
        public System.Data.DataSet EstadisticaMultas_AutoMensual(string numPlaca, short año) {
            return base.Channel.EstadisticaMultas_AutoMensual(numPlaca, año);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> EstadisticaMultas_AutoMensualAsync(string numPlaca, short año) {
            return base.Channel.EstadisticaMultas_AutoMensualAsync(numPlaca, año);
        }
        
        public System.Data.DataSet EstadisticaPapeletas_AutoAnual(string numPlaca) {
            return base.Channel.EstadisticaPapeletas_AutoAnual(numPlaca);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> EstadisticaPapeletas_AutoAnualAsync(string numPlaca) {
            return base.Channel.EstadisticaPapeletas_AutoAnualAsync(numPlaca);
        }
    }
}
