//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClienteWEBNetFramework.ServicioAuto {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServicioAuto.WS_AutoSoap")]
    public interface WS_AutoSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CalcularMulta", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        float CalcularMulta(string strNumPlaca);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CalcularMulta", ReplyAction="*")]
        System.Threading.Tasks.Task<float> CalcularMultaAsync(string strNumPlaca);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AutoPropietario", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string AutoPropietario(string strNumPlaca);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AutoPropietario", ReplyAction="*")]
        System.Threading.Tasks.Task<string> AutoPropietarioAsync(string strNumPlaca);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/PapeletasImpagas", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet PapeletasImpagas(string strNumPlaca);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/PapeletasImpagas", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> PapeletasImpagasAsync(string strNumPlaca);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WS_AutoSoapChannel : ClienteWEBNetFramework.ServicioAuto.WS_AutoSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WS_AutoSoapClient : System.ServiceModel.ClientBase<ClienteWEBNetFramework.ServicioAuto.WS_AutoSoap>, ClienteWEBNetFramework.ServicioAuto.WS_AutoSoap {
        
        public WS_AutoSoapClient() {
        }
        
        public WS_AutoSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WS_AutoSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WS_AutoSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WS_AutoSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public float CalcularMulta(string strNumPlaca) {
            return base.Channel.CalcularMulta(strNumPlaca);
        }
        
        public System.Threading.Tasks.Task<float> CalcularMultaAsync(string strNumPlaca) {
            return base.Channel.CalcularMultaAsync(strNumPlaca);
        }
        
        public string AutoPropietario(string strNumPlaca) {
            return base.Channel.AutoPropietario(strNumPlaca);
        }
        
        public System.Threading.Tasks.Task<string> AutoPropietarioAsync(string strNumPlaca) {
            return base.Channel.AutoPropietarioAsync(strNumPlaca);
        }
        
        public System.Data.DataSet PapeletasImpagas(string strNumPlaca) {
            return base.Channel.PapeletasImpagas(strNumPlaca);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> PapeletasImpagasAsync(string strNumPlaca) {
            return base.Channel.PapeletasImpagasAsync(strNumPlaca);
        }
    }
}
