//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCF_Ventas
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tb_Detalle_Compra
    {
        public string Num_oco { get; set; }
        public string Cod_pro { get; set; }
        public Nullable<int> Can_ped { get; set; }
    
        public virtual Tb_Producto Tb_Producto { get; set; }
        public virtual Tb_Orden_Compra Tb_Orden_Compra { get; set; }
    }
}
