//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCF_Ventas
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tb_Detalle_Factura
    {
        public string Num_fac { get; set; }
        public string Cod_pro { get; set; }
        public int Can_ven { get; set; }
        public float Pre_ven { get; set; }
    
        public virtual Tb_Producto Tb_Producto { get; set; }
        public virtual Tb_Factura Tb_Factura { get; set; }
    }
}
