//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCF_Ventas
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tb_Factura
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tb_Factura()
        {
            this.Tb_Detalle_Factura = new HashSet<Tb_Detalle_Factura>();
        }
    
        public string Num_fac { get; set; }
        public System.DateTime Fec_fac { get; set; }
        public string Cod_cli { get; set; }
        public Nullable<System.DateTime> Fec_can { get; set; }
        public Nullable<int> Est_fac { get; set; }
        public string Cod_ven { get; set; }
        public decimal Por_Igv { get; set; }
        public Nullable<System.DateTime> Fec_Registro { get; set; }
        public string Usu_Registro { get; set; }
        public Nullable<System.DateTime> Fec_Ult_Mod { get; set; }
        public string Usu_Ult_Mod { get; set; }
    
        public virtual Tb_Cliente Tb_Cliente { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tb_Detalle_Factura> Tb_Detalle_Factura { get; set; }
        public virtual Tb_Vendedor Tb_Vendedor { get; set; }
    }
}
