//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCF_Ventas
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tb_Vendedor
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tb_Vendedor()
        {
            this.Tb_Factura = new HashSet<Tb_Factura>();
            this.Tb_Ubigeo = new HashSet<Tb_Ubigeo>();
            this.Tb_Vendedor1 = new HashSet<Tb_Vendedor>();
        }
    
        public string Cod_ven { get; set; }
        public string Nom_ven { get; set; }
        public string Ape_ven { get; set; }
        public Nullable<decimal> Sue_ven { get; set; }
        public Nullable<System.DateTime> Fec_ing { get; set; }
        public Nullable<int> Tip_ven { get; set; }
        public string Dni_ven { get; set; }
        public string Email_ven { get; set; }
        public string Cod_Supervisor { get; set; }
        public Nullable<System.DateTime> Fec_Registro { get; set; }
        public string Usu_Registro { get; set; }
        public Nullable<System.DateTime> Fec_Ult_Mod { get; set; }
        public string Usu_Ult_Mod { get; set; }
        public Nullable<int> Est_ven { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tb_Factura> Tb_Factura { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tb_Ubigeo> Tb_Ubigeo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tb_Vendedor> Tb_Vendedor1 { get; set; }
        public virtual Tb_Vendedor Tb_Vendedor2 { get; set; }
    }
}
