//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProxyFactura
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FacturaDC", Namespace="http://schemas.datacontract.org/2004/07/WCF_Ventas")]
    public partial class FacturaDC : object
    {
        
        private string ApeNom_VenField;
        
        private string Cod_CliField;
        
        private string Cod_VenField;
        
        private string Est_DesField;
        
        private short Est_FacField;
        
        private System.Nullable<System.DateTime> Fecha_CanField;
        
        private System.DateTime Fecha_FacField;
        
        private string Num_FacField;
        
        private string Raz_soc_CliField;
        
        private float TotalField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ApeNom_Ven
        {
            get
            {
                return this.ApeNom_VenField;
            }
            set
            {
                this.ApeNom_VenField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Cod_Cli
        {
            get
            {
                return this.Cod_CliField;
            }
            set
            {
                this.Cod_CliField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Cod_Ven
        {
            get
            {
                return this.Cod_VenField;
            }
            set
            {
                this.Cod_VenField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Est_Des
        {
            get
            {
                return this.Est_DesField;
            }
            set
            {
                this.Est_DesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short Est_Fac
        {
            get
            {
                return this.Est_FacField;
            }
            set
            {
                this.Est_FacField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> Fecha_Can
        {
            get
            {
                return this.Fecha_CanField;
            }
            set
            {
                this.Fecha_CanField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Fecha_Fac
        {
            get
            {
                return this.Fecha_FacField;
            }
            set
            {
                this.Fecha_FacField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Num_Fac
        {
            get
            {
                return this.Num_FacField;
            }
            set
            {
                this.Num_FacField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Raz_soc_Cli
        {
            get
            {
                return this.Raz_soc_CliField;
            }
            set
            {
                this.Raz_soc_CliField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public float Total
        {
            get
            {
                return this.TotalField;
            }
            set
            {
                this.TotalField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ProxyFactura.IServicioFactura")]
    public interface IServicioFactura
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioFactura/ListarFacturasClienteFechas", ReplyAction="http://tempuri.org/IServicioFactura/ListarFacturasClienteFechasResponse")]
        System.Collections.Generic.List<ProxyFactura.FacturaDC> ListarFacturasClienteFechas(string strCodigo, System.DateTime fecIni, System.DateTime fecFin);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioFactura/ListarFacturasClienteFechas", ReplyAction="http://tempuri.org/IServicioFactura/ListarFacturasClienteFechasResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<ProxyFactura.FacturaDC>> ListarFacturasClienteFechasAsync(string strCodigo, System.DateTime fecIni, System.DateTime fecFin);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    public interface IServicioFacturaChannel : ProxyFactura.IServicioFactura, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    public partial class ServicioFacturaClient : System.ServiceModel.ClientBase<ProxyFactura.IServicioFactura>, ProxyFactura.IServicioFactura
    {
        
        /// <summary>
        /// Implemente este método parcial para configurar el punto de conexión de servicio.
        /// </summary>
        /// <param name="serviceEndpoint">El punto de conexión para configurar</param>
        /// <param name="clientCredentials">Credenciales de cliente</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public ServicioFacturaClient() : 
                base(ServicioFacturaClient.GetDefaultBinding(), ServicioFacturaClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_IServicioFactura.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServicioFacturaClient(EndpointConfiguration endpointConfiguration) : 
                base(ServicioFacturaClient.GetBindingForEndpoint(endpointConfiguration), ServicioFacturaClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServicioFacturaClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(ServicioFacturaClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServicioFacturaClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(ServicioFacturaClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServicioFacturaClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Collections.Generic.List<ProxyFactura.FacturaDC> ListarFacturasClienteFechas(string strCodigo, System.DateTime fecIni, System.DateTime fecFin)
        {
            return base.Channel.ListarFacturasClienteFechas(strCodigo, fecIni, fecFin);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<ProxyFactura.FacturaDC>> ListarFacturasClienteFechasAsync(string strCodigo, System.DateTime fecIni, System.DateTime fecFin)
        {
            return base.Channel.ListarFacturasClienteFechasAsync(strCodigo, fecIni, fecFin);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IServicioFactura))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IServicioFactura))
            {
                return new System.ServiceModel.EndpointAddress("http://localhost:8733/Design_Time_Addresses/WCF_Ventas/ServicioFactura/");
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return ServicioFacturaClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_IServicioFactura);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return ServicioFacturaClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_IServicioFactura);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_IServicioFactura,
        }
    }
}
