//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProxyCliente
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ClienteDC", Namespace="http://schemas.datacontract.org/2004/07/WCF_Ventas")]
    public partial class ClienteDC : object
    {
        
        private short Cant_FacturasPendientesField;
        
        private string Cod_cliField;
        
        private string ContactoField;
        
        private string DepartamentoField;
        
        private float DeudaField;
        
        private string Dir_cliField;
        
        private string DistritoField;
        
        private short Est_cliField;
        
        private System.DateTime Fec_regField;
        
        private string ProvinciaField;
        
        private string Raz_soc_cliField;
        
        private string Ruc_cliField;
        
        private string Tel_cliField;
        
        private short Tip_cliField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short Cant_FacturasPendientes
        {
            get
            {
                return this.Cant_FacturasPendientesField;
            }
            set
            {
                this.Cant_FacturasPendientesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Cod_cli
        {
            get
            {
                return this.Cod_cliField;
            }
            set
            {
                this.Cod_cliField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Contacto
        {
            get
            {
                return this.ContactoField;
            }
            set
            {
                this.ContactoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Departamento
        {
            get
            {
                return this.DepartamentoField;
            }
            set
            {
                this.DepartamentoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public float Deuda
        {
            get
            {
                return this.DeudaField;
            }
            set
            {
                this.DeudaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Dir_cli
        {
            get
            {
                return this.Dir_cliField;
            }
            set
            {
                this.Dir_cliField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Distrito
        {
            get
            {
                return this.DistritoField;
            }
            set
            {
                this.DistritoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short Est_cli
        {
            get
            {
                return this.Est_cliField;
            }
            set
            {
                this.Est_cliField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Fec_reg
        {
            get
            {
                return this.Fec_regField;
            }
            set
            {
                this.Fec_regField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Provincia
        {
            get
            {
                return this.ProvinciaField;
            }
            set
            {
                this.ProvinciaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Raz_soc_cli
        {
            get
            {
                return this.Raz_soc_cliField;
            }
            set
            {
                this.Raz_soc_cliField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Ruc_cli
        {
            get
            {
                return this.Ruc_cliField;
            }
            set
            {
                this.Ruc_cliField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Tel_cli
        {
            get
            {
                return this.Tel_cliField;
            }
            set
            {
                this.Tel_cliField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short Tip_cli
        {
            get
            {
                return this.Tip_cliField;
            }
            set
            {
                this.Tip_cliField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ProxyCliente.IServicioCliente")]
    public interface IServicioCliente
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioCliente/ConsultarCliente", ReplyAction="http://tempuri.org/IServicioCliente/ConsultarClienteResponse")]
        ProxyCliente.ClienteDC ConsultarCliente(string strCodigo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioCliente/ConsultarCliente", ReplyAction="http://tempuri.org/IServicioCliente/ConsultarClienteResponse")]
        System.Threading.Tasks.Task<ProxyCliente.ClienteDC> ConsultarClienteAsync(string strCodigo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioCliente/CalcularDeudaCliente", ReplyAction="http://tempuri.org/IServicioCliente/CalcularDeudaClienteResponse")]
        float CalcularDeudaCliente(string strCodigo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioCliente/CalcularDeudaCliente", ReplyAction="http://tempuri.org/IServicioCliente/CalcularDeudaClienteResponse")]
        System.Threading.Tasks.Task<float> CalcularDeudaClienteAsync(string strCodigo);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    public interface IServicioClienteChannel : ProxyCliente.IServicioCliente, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    public partial class ServicioClienteClient : System.ServiceModel.ClientBase<ProxyCliente.IServicioCliente>, ProxyCliente.IServicioCliente
    {
        
        /// <summary>
        /// Implemente este método parcial para configurar el punto de conexión de servicio.
        /// </summary>
        /// <param name="serviceEndpoint">El punto de conexión para configurar</param>
        /// <param name="clientCredentials">Credenciales de cliente</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public ServicioClienteClient() : 
                base(ServicioClienteClient.GetDefaultBinding(), ServicioClienteClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_IServicioCliente.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServicioClienteClient(EndpointConfiguration endpointConfiguration) : 
                base(ServicioClienteClient.GetBindingForEndpoint(endpointConfiguration), ServicioClienteClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServicioClienteClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(ServicioClienteClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServicioClienteClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(ServicioClienteClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServicioClienteClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public ProxyCliente.ClienteDC ConsultarCliente(string strCodigo)
        {
            return base.Channel.ConsultarCliente(strCodigo);
        }
        
        public System.Threading.Tasks.Task<ProxyCliente.ClienteDC> ConsultarClienteAsync(string strCodigo)
        {
            return base.Channel.ConsultarClienteAsync(strCodigo);
        }
        
        public float CalcularDeudaCliente(string strCodigo)
        {
            return base.Channel.CalcularDeudaCliente(strCodigo);
        }
        
        public System.Threading.Tasks.Task<float> CalcularDeudaClienteAsync(string strCodigo)
        {
            return base.Channel.CalcularDeudaClienteAsync(strCodigo);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IServicioCliente))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IServicioCliente))
            {
                return new System.ServiceModel.EndpointAddress("http://localhost:8733/Design_Time_Addresses/WCF_Ventas/ServicioCliente/");
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return ServicioClienteClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_IServicioCliente);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return ServicioClienteClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_IServicioCliente);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_IServicioCliente,
        }
    }
}
