//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProxyVendedor
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="VendedorDC", Namespace="http://schemas.datacontract.org/2004/07/WCF_Ventas")]
    public partial class VendedorDC : object
    {
        
        private string Ape_venField;
        
        private string ApellNom_SupervisorField;
        
        private string Cod_SupervisorField;
        
        private string Cod_venField;
        
        private string DNI_venField;
        
        private string Email_venField;
        
        private System.Nullable<int> Est_venField;
        
        private string EstadoField;
        
        private System.Nullable<System.DateTime> Fec_RegistroField;
        
        private System.Nullable<System.DateTime> Fec_Ult_ModField;
        
        private System.DateTime Fec_ingField;
        
        private string Nom_venField;
        
        private System.Nullable<decimal> Sue_venField;
        
        private short Tip_venField;
        
        private string Usu_RegistroField;
        
        private string Usu_Ult_ModField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Ape_ven
        {
            get
            {
                return this.Ape_venField;
            }
            set
            {
                this.Ape_venField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ApellNom_Supervisor
        {
            get
            {
                return this.ApellNom_SupervisorField;
            }
            set
            {
                this.ApellNom_SupervisorField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Cod_Supervisor
        {
            get
            {
                return this.Cod_SupervisorField;
            }
            set
            {
                this.Cod_SupervisorField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Cod_ven
        {
            get
            {
                return this.Cod_venField;
            }
            set
            {
                this.Cod_venField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DNI_ven
        {
            get
            {
                return this.DNI_venField;
            }
            set
            {
                this.DNI_venField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email_ven
        {
            get
            {
                return this.Email_venField;
            }
            set
            {
                this.Email_venField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Est_ven
        {
            get
            {
                return this.Est_venField;
            }
            set
            {
                this.Est_venField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Estado
        {
            get
            {
                return this.EstadoField;
            }
            set
            {
                this.EstadoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> Fec_Registro
        {
            get
            {
                return this.Fec_RegistroField;
            }
            set
            {
                this.Fec_RegistroField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> Fec_Ult_Mod
        {
            get
            {
                return this.Fec_Ult_ModField;
            }
            set
            {
                this.Fec_Ult_ModField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Fec_ing
        {
            get
            {
                return this.Fec_ingField;
            }
            set
            {
                this.Fec_ingField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nom_ven
        {
            get
            {
                return this.Nom_venField;
            }
            set
            {
                this.Nom_venField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> Sue_ven
        {
            get
            {
                return this.Sue_venField;
            }
            set
            {
                this.Sue_venField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short Tip_ven
        {
            get
            {
                return this.Tip_venField;
            }
            set
            {
                this.Tip_venField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Usu_Registro
        {
            get
            {
                return this.Usu_RegistroField;
            }
            set
            {
                this.Usu_RegistroField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Usu_Ult_Mod
        {
            get
            {
                return this.Usu_Ult_ModField;
            }
            set
            {
                this.Usu_Ult_ModField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ProxyVendedor.IServicioVendedor")]
    public interface IServicioVendedor
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioVendedor/ConsultarVendedor", ReplyAction="http://tempuri.org/IServicioVendedor/ConsultarVendedorResponse")]
        ProxyVendedor.VendedorDC ConsultarVendedor(string strCodigo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioVendedor/ConsultarVendedor", ReplyAction="http://tempuri.org/IServicioVendedor/ConsultarVendedorResponse")]
        System.Threading.Tasks.Task<ProxyVendedor.VendedorDC> ConsultarVendedorAsync(string strCodigo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioVendedor/ListarVendedor", ReplyAction="http://tempuri.org/IServicioVendedor/ListarVendedorResponse")]
        System.Collections.Generic.List<ProxyVendedor.VendedorDC> ListarVendedor();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioVendedor/ListarVendedor", ReplyAction="http://tempuri.org/IServicioVendedor/ListarVendedorResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<ProxyVendedor.VendedorDC>> ListarVendedorAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioVendedor/InsertarVendedor", ReplyAction="http://tempuri.org/IServicioVendedor/InsertarVendedorResponse")]
        bool InsertarVendedor(ProxyVendedor.VendedorDC objVendedorDC);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioVendedor/InsertarVendedor", ReplyAction="http://tempuri.org/IServicioVendedor/InsertarVendedorResponse")]
        System.Threading.Tasks.Task<bool> InsertarVendedorAsync(ProxyVendedor.VendedorDC objVendedorDC);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioVendedor/ActualizarVendedor", ReplyAction="http://tempuri.org/IServicioVendedor/ActualizarVendedorResponse")]
        bool ActualizarVendedor(ProxyVendedor.VendedorDC objVendedorDC);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioVendedor/ActualizarVendedor", ReplyAction="http://tempuri.org/IServicioVendedor/ActualizarVendedorResponse")]
        System.Threading.Tasks.Task<bool> ActualizarVendedorAsync(ProxyVendedor.VendedorDC objVendedorDC);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioVendedor/EliminarVendedor", ReplyAction="http://tempuri.org/IServicioVendedor/EliminarVendedorResponse")]
        bool EliminarVendedor(string strCodigo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioVendedor/EliminarVendedor", ReplyAction="http://tempuri.org/IServicioVendedor/EliminarVendedorResponse")]
        System.Threading.Tasks.Task<bool> EliminarVendedorAsync(string strCodigo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioVendedor/ListarSupervisores", ReplyAction="http://tempuri.org/IServicioVendedor/ListarSupervisoresResponse")]
        System.Collections.Generic.List<ProxyVendedor.VendedorDC> ListarSupervisores();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioVendedor/ListarSupervisores", ReplyAction="http://tempuri.org/IServicioVendedor/ListarSupervisoresResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<ProxyVendedor.VendedorDC>> ListarSupervisoresAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    public interface IServicioVendedorChannel : ProxyVendedor.IServicioVendedor, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    public partial class ServicioVendedorClient : System.ServiceModel.ClientBase<ProxyVendedor.IServicioVendedor>, ProxyVendedor.IServicioVendedor
    {
        
        /// <summary>
        /// Implemente este método parcial para configurar el punto de conexión de servicio.
        /// </summary>
        /// <param name="serviceEndpoint">El punto de conexión para configurar</param>
        /// <param name="clientCredentials">Credenciales de cliente</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public ServicioVendedorClient() : 
                base(ServicioVendedorClient.GetDefaultBinding(), ServicioVendedorClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_IServicioVendedor.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServicioVendedorClient(EndpointConfiguration endpointConfiguration) : 
                base(ServicioVendedorClient.GetBindingForEndpoint(endpointConfiguration), ServicioVendedorClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServicioVendedorClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(ServicioVendedorClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServicioVendedorClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(ServicioVendedorClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServicioVendedorClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public ProxyVendedor.VendedorDC ConsultarVendedor(string strCodigo)
        {
            return base.Channel.ConsultarVendedor(strCodigo);
        }
        
        public System.Threading.Tasks.Task<ProxyVendedor.VendedorDC> ConsultarVendedorAsync(string strCodigo)
        {
            return base.Channel.ConsultarVendedorAsync(strCodigo);
        }
        
        public System.Collections.Generic.List<ProxyVendedor.VendedorDC> ListarVendedor()
        {
            return base.Channel.ListarVendedor();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<ProxyVendedor.VendedorDC>> ListarVendedorAsync()
        {
            return base.Channel.ListarVendedorAsync();
        }
        
        public bool InsertarVendedor(ProxyVendedor.VendedorDC objVendedorDC)
        {
            return base.Channel.InsertarVendedor(objVendedorDC);
        }
        
        public System.Threading.Tasks.Task<bool> InsertarVendedorAsync(ProxyVendedor.VendedorDC objVendedorDC)
        {
            return base.Channel.InsertarVendedorAsync(objVendedorDC);
        }
        
        public bool ActualizarVendedor(ProxyVendedor.VendedorDC objVendedorDC)
        {
            return base.Channel.ActualizarVendedor(objVendedorDC);
        }
        
        public System.Threading.Tasks.Task<bool> ActualizarVendedorAsync(ProxyVendedor.VendedorDC objVendedorDC)
        {
            return base.Channel.ActualizarVendedorAsync(objVendedorDC);
        }
        
        public bool EliminarVendedor(string strCodigo)
        {
            return base.Channel.EliminarVendedor(strCodigo);
        }
        
        public System.Threading.Tasks.Task<bool> EliminarVendedorAsync(string strCodigo)
        {
            return base.Channel.EliminarVendedorAsync(strCodigo);
        }
        
        public System.Collections.Generic.List<ProxyVendedor.VendedorDC> ListarSupervisores()
        {
            return base.Channel.ListarSupervisores();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<ProxyVendedor.VendedorDC>> ListarSupervisoresAsync()
        {
            return base.Channel.ListarSupervisoresAsync();
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IServicioVendedor))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IServicioVendedor))
            {
                return new System.ServiceModel.EndpointAddress("http://localhost:8733/Design_Time_Addresses/WCF_Ventas/ServicioVendedor/");
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return ServicioVendedorClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_IServicioVendedor);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return ServicioVendedorClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_IServicioVendedor);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_IServicioVendedor,
        }
    }
}
